feat: collecting all configs to one place and some refactoring
KenshiTech/unchained pull request #101
Opened 2024-03-28 14:36 UTC by logicalangel

2024-03-28 15:27 UTC, pouya-eghbali submitted a review, later dismissed

2024-03-31 09:43 UTC, pouya-eghbali requested changes

2024-03-31 09:43 UTC, pouya-eghbali commented on conf.standalone.yaml.template
>      - https://sepolia-rollup.arbitrum.io/rpc
Doesn't look like the indentation is correct for -nodes

2024-03-31 14:16 UTC, logicalangel commented on conf.standalone.yaml.template
>      - https://sepolia-rollup.arbitrum.io/rpc
It is an object in the list which have name and nodes as property

2024-03-31 14:47 UTC, pouya-eghbali approved these changes

2024-03-31 14:49 UTC, merged