Fix remove go work 97
KenshiTech/unchained pull request #119
Opened 2024-04-05 00:01 UTC by logicalangel

2024-04-05 00:11 UTC, logicalangel commented
depend on #107 
and resolve #119

2024-04-08 09:28 UTC, pouya-eghbali requested changes

2024-04-08 09:28 UTC, pouya-eghbali commented on docker/Dockerfile
> +    curl -sSL https://github.com/KenshiTech/unchained/internal/releases/download/${UNCHAINED_VERSION}/unchained.${TARGETOS}.${TARGETARCH} -o unchained && \
this one should have /internal/

2024-04-08 09:28 UTC, pouya-eghbali commented on Readme.md
> +[![Release](https://shields.io/github/v/release/kenshitech/unchained)](https://github.com/KenshiTech/unchained/internal/releases)
This should not have /internal/

2024-04-08 09:28 UTC, pouya-eghbali commented on Readme.md
> +[![Image tags](https://ghcrbadge-1-y2886489.deta.app/kenshitech/unchained/tags?color=%2344cc11&ignore=latest&n=1&label=image+tags&trim=)](https://github.com/KenshiTech/unchained/internal/pkgs/contain
This should not have /internal/

2024-04-08 09:28 UTC, pouya-eghbali commented on Readme.md
> +[![Image size](https://ghcrbadge-1-y2886489.deta.app/kenshitech/unchained/size?color=%2344cc11&tag=latest&label=image+size&trim=)](https://github.com/KenshiTech/unchained/internal/pkgs/container/unch
This should not have /internal/

2024-04-08 09:28 UTC, pouya-eghbali commented on Readme.md
> +[unchained.demo.webm](https://github.com/KenshiTech/unchained/internal/assets/4604055/427740a2-799c-42e2-a863-f44cc6e74d46)
This should not have /internal/

2024-04-08 09:28 UTC, pouya-eghbali commented on Readme.md
> +<a href="https://github.com/KenshiTech/unchained/internal/graphs/contributors">
This should not have /internal/

2024-04-11 09:20 UTC, pouya-eghbali requested changes

2024-04-11 09:20 UTC, pouya-eghbali commented on quickstart.md
> +[Unchained release page](https://github.com/KenshiTech/unchained/internal/releases)
This one shouldn't have /internal/

2024-04-11 16:35 UTC, merged