Fix cobra 98
KenshiTech/unchained pull request #122
Opened 2024-04-07 22:29 UTC by logicalangel

2024-04-12 19:25 UTC, pouya-eghbali requested changes

2024-04-12 19:25 UTC, pouya-eghbali commented on internal/config/config.go
> +		pureLog.Println("Can't load secrets")
why

2024-04-12 19:25 UTC, pouya-eghbali commented on internal/config/model.go
> +	Log  string `env:"SYSTEM_LOG"  env-default:"debug"     yaml:"log"`
default should be info

2024-04-12 19:25 UTC, pouya-eghbali commented on internal/crypto/ethereum/rpc.go
> +	contracts2 "github.com/KenshiTech/unchained/internal/crypto/ethereum/contracts"
contracts2?

2024-04-12 19:25 UTC, pouya-eghbali commented on internal/crypto/identity.go
> +package crypto
this should be moved to internal/crypto/secp256k1/identity.go

2024-04-12 19:25 UTC, pouya-eghbali commented on internal/service/uniswap/uniswap.go
> +	if !isMajority {
Check the file;

```go
	DebouncedSaveSignatures(
		info.Asset,
		SaveSignatureArgs{Hash: hash, Info: info},
	)
```

and 

```go
	if !isMajority {
		log.Logger.Debug("Not a majority")
	}
```

are duplicated. Are there any other duplicates in other files??

2024-04-12 19:29 UTC, logicalangel commented on internal/config/config.go
> +		pureLog.Println("Can't load secrets")
You know that we read the logger level from the configurations. These codes are loaded before initializing the logger. Before this PR, the logger's level which is passed to the logger was empty.

2024-04-14 18:36 UTC, pouya-eghbali approved these changes

2024-04-14 19:33 UTC, merged